name: Deploy Next.js app to Azure App Service

on:
  push:
    branches:
      - main   # deploy automatically on push to main
  workflow_dispatch:   # allows manual run from GitHub Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Zip build for deployment
        run: zip -r build.zip .next public package.json node_modules prisma

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mwa-intranet
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build.zip
