# ================================================================
#   GitHub Action: Build and Deploy Next.js App to Azure App Service
# ================================================================
# This workflow builds the app, syncs Prisma schema, and deploys
# to the Azure Web App "mwa-intranet" using the publish profile.
# ================================================================

name: Build and deploy Node.js app to Azure Web App - mwa-intranet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js 20 and cache dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Clean install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Rebuild Prisma client and push schema (mirrors SSH steps)
      - name: Prepare Prisma client
        run: |
          npm rebuild @prisma/client
          npx prisma generate
          npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Step 5: Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Step 6: Package build for deployment
      - name: Package app
        run: zip -r node-app.zip .next public package.json node_modules prisma next.config.mjs

      # Step 7: Upload artifact for deploy step
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      # Step 8: Download built artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Step 9: Deploy to Azure App Service using publish profile
      - name: Deploy to Azure Web App
        uses: azure/
